# For local
# https://medium.com/@shakyShane/laravel-docker-part-1-setup-for-development-e3daaefaf3c
# For production
# https://medium.com/@shakyShane/laravel-docker-part-2-preparing-for-production-9c6a024e9797

version: '2'
services:
  api:
    build:
      context: ./
      dockerfile: docker/api.dockerfile
    working_dir: /var/www/api
    volumes:
      - ./:/var/www/api
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www/api
    volumes_from:
      - api
    ports:
      - 8080:80
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
    volumes: []