# For local
# https://medium.com/@shakyShane/laravel-docker-part-1-setup-for-development-e3daaefaf3c
# For production
# https://medium.com/@shakyShane/laravel-docker-part-2-preparing-for-production-9c6a024e9797

version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: docker/api.dockerfile
    container_name: village_api
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  app:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    container_name: village_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: village_db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
        - "33061:3306"
    volumes: []