
export const postActions = {
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POSTS_PENDING: 'FETCH_POSTS_PENDING',
  FETCH_POSTS_FULFILLED: 'FETCH_POSTS_FULFILLED',
  FETCH_POST: 'FETCH_POST',
  FETCH_POST_PENDING: 'FETCH_POST_PENDING',
  FETCH_POST_FULFILLED: 'FETCH_POST_FULFILLED',
  UPDATE_POST: 'UPDATE_POST',
  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  REQUEST_UPDATE_POST: 'REQUEST_UPDATE_POST'
}

export const ADD_COMMENT = 'ADD_COMMENT'
export const PERSIST_COMMENT = 'PERSIST_COMMENT'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'

export const ADD_TAG_TO_POST = 'ADD_TAG_TO_POST'
export const REMOVE_TAG_FROM_POST = 'REMOVE_TAG_FROM_POST'

export const SELECT_USER = 'SELECT_USER'