export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POST = 'FETCH_POST'
export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'

export const ADD_COMMENT = 'ADD_COMMENT'
export const PERSIST_COMMENT = 'PERSIST_COMMENT'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'

export const ADD_TAG_TO_POST = 'ADD_TAG_TO_POST'
export const REMOVE_TAG_FROM_POST = 'REMOVE_TAG_FROM_POST'

export const SELECT_USER = 'SELECT_USER'